name: multi-stage-workflow
on:
   workflow_dispatch:
   #schedule:
      #- cron: '0 0 * * *'(UTC TimeZone)
    inputs:
      myInput:
         description: 'provide simple input'
         required: true
         default: 'Hello World'
jobs:
    build:
       runs-on: ubuntu-latest
       steps:
          - uses: actions/checkout@v4
          - name: 'Run a script'
            run: echo hello
    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
          - uses: actions/checkout@v4
          - name: 'Run a script'
            run: echo hello
