name: Release action

# Release your solution to prod when you create a new release.
on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  Release-solution-ALMLab:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Pack solution
        uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-folder: solutions/dev_sol
          solution-file: out/solutions/dev_sol.zip
          solution-type: Unmanaged

      - name: Export solution as managed
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url: 'https://orgb2838d04.crm8.dynamics.com'
          app-id: '227a6a7e-3558-47d4-babb-8a7372d45806'
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: '2186f566-2dc1-44e4-bec4-67814bcbd96b'
          solution-name: dev_sol
          managed: true
          solution-output-file: out/ship/dev_sol_managed.zip

      - name: Upload the ready to ship solution to GH artifact store
        uses: actions/upload-artifact@v2
        with:
          name: managedSolutions
          path: out/ship/

  release-to-staging:
    needs: [Release-solution-ALMLab]
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Fetch the ready to ship solution from GH artifact store
        uses: actions/download-artifact@v2
        with:
          name: managedSolutions
          path: out/release

      - name: Import solution to prod env
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: 'https://org2658f4e7.crm8.dynamics.com'
          app-id: '227a6a7e-3558-47d4-babb-8a7372d45806'
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: '2186f566-2dc1-44e4-bec4-67814bcbd96b'
          solution-file: out/release/dev_sol_managed.zip
          force-overwrite: true
          publish-changes: true
