name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.
 on: 
permissions:
  contents: write
jobs:
  Release-solution-ALMLab:
    #uses: deepikathummala/Powerapps/.github/workflows/release-solution-to-prod-with-inputs.yml@main
    with:
      #You can specify the solution name here
      solution_name: dev_sol
      #Update your values here
      BUILD_ENVIRONMENT_URL: 'https://org70923278.crm8.dynamics.com/'
      PRODUCTION_ENVIRONMENT_URL:  'https://org2658f4e7.crm8.dynamics.com/'
      CLIENT_ID: '56c05d4d-4993-462c-918d-5d330f2c1106'
      TENANT_ID: '2186f566-2dc1-44e4-bec4-67814bcbd96b'      
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-folder: ${{ inputs.solution_source_folder}}/${{ inputs.solution_name }}
        solution-file: ${{ inputs.solution_outbound_folder}}/${{ inputs.solution_name }}.zip
        solution-type: Unmanaged

   # - name: Import solution as unmanaged to build env
       #uses: microsoft/powerplatform-actions/import-solution@v0
      # with:
        #environment-url: ${{inputs.BUILD_ENVIRONMENT_URL}}
        #app-id: ${{inputs.CLIENT_ID}}
        #client-secret: ${{ secrets.envSecret }}
        #tenant-id: ${{inputs.TENANT_ID}}
        #solution-file: ${{ inputs.solution_outbound_folder}}/${{ inputs.solution_name }}.zip
        #force-overwrite: true
        #publish-changes: true

    - name: Export solution as managed
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{inputs.BUILD_ENVIRONMENT_URL}}
        app-id: ${{inputs.CLIENT_ID}}
        client-secret: ${{ secrets.envSecret }} 
        tenant-id: ${{inputs.TENANT_ID}}
        solution-name: ${{ inputs.solution_name }}
        managed: true
        solution-output-file: ${{ inputs.solution_shipping_folder}}/${{ inputs.solution_name }}_managed.zip

    - name: Upload the ready to ship solution to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: ${{ inputs.solution_shipping_folder}}/

  release-to-staging:
    needs: [ convert-to-managed ]
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: ${{ inputs.solution_release_folder}}
    - name: Import solution to prod env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{inputs.PRODUCTION_ENVIRONMENT_URL}}
        app-id: ${{inputs.CLIENT_ID}}
        client-secret: ${{ secrets.envSecret }}
        tenant-id: ${{inputs.TENANT_ID}}
        solution-file: ${{ inputs.solution_release_folder}}/${{ inputs.solution_name }}_managed.zip
        force-overwrite: true
        publish-changes: true
